CREATE EXTENSION IF NOT EXISTS vector;

-- One row per ingested source. The lifecycle lives here.
CREATE TABLE IF NOT EXISTS sources (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competitor    TEXT NOT NULL,
    axis          TEXT NOT NULL CHECK (axis IN ('technical','business','both')),
    doc_type      TEXT NOT NULL,
    dimension     TEXT,                       -- which ontology dimension this source informs
    url           TEXT NOT NULL,
    title         TEXT,
    publish_date  DATE,
    fetched_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    content_hash  TEXT NOT NULL,              -- dedup: same hash => unchanged, skip re-embed
    status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active','stale','superseded','dead')),
    raw_path      TEXT,                        -- snapshot path for provenance
    UNIQUE (url, content_hash)
);

-- One row per chunk of COMPILED competitor knowledge. Metadata denormalized for fast filtering.
CREATE TABLE IF NOT EXISTS chunks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id     BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    competitor    TEXT NOT NULL,
    axis          TEXT NOT NULL,
    doc_type      TEXT NOT NULL,
    publish_date  DATE,
    status        TEXT NOT NULL DEFAULT 'active',
    chunk_text    TEXT NOT NULL,
    embedding     VECTOR(1536) NOT NULL
);

-- The graph: entities and the edges between them. Populated by the synthesis step.
CREATE TABLE IF NOT EXISTS entities (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    entity_type  TEXT NOT NULL,               -- competitor | product | feature | integration | ...
    competitor   TEXT,                          -- owning competitor (null for shared concepts)
    UNIQUE (name, entity_type)
);

CREATE TABLE IF NOT EXISTS relationships (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    src_entity_id BIGINT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    dst_entity_id BIGINT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    relation      TEXT NOT NULL,               -- has_feature | integrates_with | competes_with | ...
    source_id     BIGINT REFERENCES sources(id) ON DELETE SET NULL,  -- edge provenance
    UNIQUE (src_entity_id, dst_entity_id, relation)
);

-- Vector index covering only ACTIVE chunks: filtered retrieval stays both correct and fast.
CREATE INDEX IF NOT EXISTS chunks_embedding_active_hnsw
    ON chunks USING hnsw (embedding vector_cosine_ops) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS chunks_filter_idx ON chunks (status, competitor, axis, publish_date);
CREATE INDEX IF NOT EXISTS sources_status_idx ON sources (status);
CREATE INDEX IF NOT EXISTS sources_dim_idx    ON sources (competitor, dimension, status);
