CREATE EXTENSION IF NOT EXISTS vector;

-- One row per ingested source. The lifecycle lives here.
CREATE TABLE IF NOT EXISTS sources (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competitor    TEXT NOT NULL,
    axis          TEXT NOT NULL CHECK (axis IN ('technical','business','both')),
    doc_type      TEXT NOT NULL,
    dimension     TEXT,                       -- which ontology dimension this source informs
    url           TEXT NOT NULL,
    title         TEXT,
    publish_date  DATE,
    fetched_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    content_hash  TEXT NOT NULL,              -- dedup: same hash => unchanged, skip re-embed
    status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active','stale','superseded','dead')),
    source_kind   TEXT NOT NULL DEFAULT 'unknown', -- official docs | pricing | blog | analyst | ...
    raw_path      TEXT,                        -- snapshot path for provenance
    UNIQUE (url, content_hash)
);

-- Lightweight upgrade path for databases created before source_kind existed.
ALTER TABLE sources ADD COLUMN IF NOT EXISTS source_kind TEXT NOT NULL DEFAULT 'unknown';

-- One row per chunk of COMPILED company knowledge. Metadata denormalized for fast filtering.
CREATE TABLE IF NOT EXISTS chunks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id     BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    competitor    TEXT NOT NULL,
    axis          TEXT NOT NULL,
    doc_type      TEXT NOT NULL,
    publish_date  DATE,
    status        TEXT NOT NULL DEFAULT 'active',
    chunk_text    TEXT NOT NULL,
    embedding     VECTOR(1536) NOT NULL
);

-- The graph: entities and the edges between them. Populated by the synthesis step.
CREATE TABLE IF NOT EXISTS entities (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    entity_type  TEXT NOT NULL,               -- competitor | product | feature | integration | ...
    competitor   TEXT,                          -- owning competitor (null for shared concepts)
    UNIQUE (name, entity_type)
);

CREATE TABLE IF NOT EXISTS relationships (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    src_entity_id BIGINT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    dst_entity_id BIGINT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    relation      TEXT NOT NULL,               -- has_feature | integrates_with | competes_with | ...
    source_id     BIGINT REFERENCES sources(id) ON DELETE SET NULL,  -- edge provenance
    UNIQUE (src_entity_id, dst_entity_id, relation)
);

-- Official URLs cited by a stored source, especially internal report slices.
CREATE TABLE IF NOT EXISTS source_citations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id        BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    cited_url        TEXT NOT NULL,
    citation_label   TEXT,
    cited_date_text  TEXT,
    UNIQUE (source_id, cited_url)
);

CREATE TABLE IF NOT EXISTS source_healing_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id      BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    action         TEXT NOT NULL,
    old_status     TEXT,
    new_status     TEXT,
    old_dimension  TEXT,
    new_dimension  TEXT,
    reason         TEXT NOT NULL,
    details        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dimension_coverage_assertions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id     BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    competitor    TEXT NOT NULL,
    axis          TEXT NOT NULL CHECK (axis IN ('technical','business','both')),
    dimension     TEXT NOT NULL,
    state         TEXT NOT NULL
                  CHECK (state IN ('present','partial','planned','absent','unknown')),
    confidence    DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    claim         TEXT NOT NULL,
    reason        TEXT NOT NULL,
    details       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_id, competitor, axis, dimension, state, claim)
);

CREATE TABLE IF NOT EXISTS dimension_coverage_status (
    competitor          TEXT NOT NULL,
    axis                TEXT NOT NULL CHECK (axis IN ('technical','business','both')),
    dimension           TEXT NOT NULL,
    state               TEXT NOT NULL
                        CHECK (state IN ('present','partial','planned','absent','unknown')),
    confidence          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    active_assertions   INTEGER NOT NULL DEFAULT 0,
    strongest_source_id BIGINT REFERENCES sources(id) ON DELETE SET NULL,
    conflict            BOOLEAN NOT NULL DEFAULT false,
    states              JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (competitor, axis, dimension)
);

CREATE TABLE IF NOT EXISTS dimension_coverage_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      TEXT NOT NULL,
    competitor  TEXT NOT NULL,
    axis        TEXT NOT NULL,
    dimension   TEXT NOT NULL,
    old_state   TEXT,
    new_state   TEXT,
    source_id   BIGINT REFERENCES sources(id) ON DELETE SET NULL,
    reason      TEXT NOT NULL,
    details     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Vector index covering only ACTIVE chunks: filtered retrieval stays both correct and fast.
CREATE INDEX IF NOT EXISTS chunks_embedding_active_hnsw
    ON chunks USING hnsw (embedding vector_cosine_ops) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS chunks_filter_idx ON chunks (status, competitor, axis, publish_date);
CREATE INDEX IF NOT EXISTS sources_status_idx ON sources (status);
CREATE INDEX IF NOT EXISTS sources_dim_idx    ON sources (competitor, dimension, status);
CREATE INDEX IF NOT EXISTS source_citations_source_idx ON source_citations (source_id);
CREATE INDEX IF NOT EXISTS source_healing_audit_source_idx ON source_healing_audit (source_id);
CREATE INDEX IF NOT EXISTS dimension_coverage_assertions_lookup_idx
    ON dimension_coverage_assertions (competitor, axis, dimension, state);
CREATE INDEX IF NOT EXISTS dimension_coverage_assertions_source_idx
    ON dimension_coverage_assertions (source_id);
CREATE INDEX IF NOT EXISTS dimension_coverage_assertions_source_dim_state_idx
    ON dimension_coverage_assertions (source_id, dimension, state);
CREATE INDEX IF NOT EXISTS dimension_coverage_audit_lookup_idx
    ON dimension_coverage_audit (competitor, axis, dimension);

GRANT SELECT, INSERT, UPDATE, DELETE ON
    dimension_coverage_assertions,
    dimension_coverage_status,
    dimension_coverage_audit
TO "ci-engine-sa@jfrog-intel-rag.iam";

GRANT USAGE, SELECT ON SEQUENCE
    dimension_coverage_assertions_id_seq,
    dimension_coverage_audit_id_seq
TO "ci-engine-sa@jfrog-intel-rag.iam";
